version: '3'
services:
 backend:
  build:
   context: ./
   dockerfile: docker/Dockerfile
  container_name: alarmButtons
  volumes:
   - ./data:/data
   - ./src:/src
  env_file:
   - ./docker.env 
  network_mode: host
  tty: True
