# Generated by Django 3.2.4 on 2021-06-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macAddr', models.CharField(max_length=30)),
                ('buttonNum', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('macAddr', 'buttonNum')},
            },
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macAddr', models.CharField(max_length=30)),
                ('buttonNum', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('macAddr', 'buttonNum')},
            },
        ),
    ]
